#!/usr/bin/env bash

go fmt ./...
goimports -l -w . # includes go fmt
golint ./...
go vet ./...
golangci-lint run # includes golint, go vet

file=".properties.version"
v=$(cat "$file")
echo "${v%.*}.$((${v##*.}+1))" > $file
git add .properties.version